config/routes.rb
Rails.application.routes.draw do

namespace :admin do
 root to:"homes#top"
 resources :items, only: [:index, :new, :create, :show, :edit, :update]
 resources :customers, only: [:index, :show, :edit, :update]
 resources :genres, only: [:index, :create, :edit, :update]
 patch 'order_details/:id' => 'order_details#update'
 resources :orders, only: [:show, :edit, :update]
 post 'items' => 'items#create'
 patch 'items/:id' => 'items#update'
 patch 'customers/:id/edit' => 'customers#update'
 end

devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

scope module: :public do
 get'homes/about' => 'homes#about', as: 'about'
 root to:"homes#top"
 resources :items, only: [:index, :show]
 delete '/cart_items/destroy_all' => 'cart_items#destroy_all', as: 'cart_items_destroy_all'
 resources :cart_items, only: [:index, :destroy, :create, :update]
 get 'orders/complete' => 'orders#complete'
 resources :orders, only: [:new, :create, :index, :show]
 resources :addresses, only: [:new, :index, :show, :create, :update, :destroy, :edit]
 get 'customers/unsubscribe' => 'customers#unsubscribe'
 get 'customers/information' => 'customers#show'
 resources :customers, only: [:show, :edit, :update, :destroy]
 get 'orders/confirm' => 'orders#confirm'
 patch '/customers/:id/withdrawal' => 'customers#withdrawal', as: 'withdrawal'
 post 'orders/confirm' => 'orders#confirm'
 post 'customers/information' => 'customers#new'
 end
end

app/models/address.rb
class Address < ApplicationRecord
belongs_to :customer

def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
end
end

app/models/admin.rb
class Admin < ApplicationRecord
  has_one_attached :image

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
belongs_to :customer
belongs_to :item

def subtotal
    item.with_tax_price * amount
end

end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def active_for_authentication?
    super && (is_deleted == false)
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
   has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :order_details, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  belongs_to :genre
  has_one_attached :profile_image
  ## 消費税を求めるメソッド
def with_tax_price
    (price * 1.1).floor
end

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image
  end

end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details, dependent: :destroy
  belongs_to :customer
  has_many :items, dependent: :destroy

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum is_active: { waiting_for_payment: 0, payment_confirmation: 1, in_production: 2, preparing_to_ship: 3, sent: 4 }

  def subtotal
    item.with_tax_price * amount
  end

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
 belongs_to :order
 belongs_to :item
 enum making_status: { cannot_be_manufactured: 0, waiting_for_production: 1, in_production: 2, completion_of_production: 3 }
end

app/models/post_image.rb
class PostImage < ApplicationRecord
  has_one_attached :image
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
 # def new
 #   @customer = Customer.new
 # end

 # def create
 #   @customer = Customer.find(params[:id])
 # end

 def index
   @items = Item.all
   @customers = Customer.all
   @customers = Customer.page(params[:page]).per(10)
 end

 def show
   @customer = Customer.find(params[:id])
 end

 def edit
   @customer = Customer.find(params[:id])
 end

 def update
  @customer = Customer.find(params[:id])
  @customer.update(customer_params)
  redirect_to admin_customer_path(@customer)
 end

 private
 def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number)
 end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  def new
   @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def index
  @genres = Genre.all
  @genres = Genre.page(params[:page]).per(5)
  end

  def show
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end

  private
  def genre_params
    params.require(:genre).permit(:name)
  end

  def item_params
    params.require(:item).permit(:profile_image, :name, :introduction, :price, :is_active)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

 def top
  @order = Order.all
  @order_details = OrderDetail.page(params[:page]).per(10)
  @total = 0
 end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def new
  @item = Item.new
  end

  def create
  @item = Item.new(item_params)
  @item.save
  redirect_to admin_item_path(@item.id)
  end

  def index
  @items = Item.all
  @items = Item.page(params[:page]).per(10)
  @genres = Genre.all
  end

  def show
  @post_image = PostImage.new
  @item = Item.find(params[:id])
  @items = Item.all
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :price, :is_active, :profile_image, :genre_id)
  end

  def genre_params
    params.require(:genre).permit(:name)
  end

  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    customers_information_path(current_customer.id)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <h4 class="row mt-4 bg-light bold">
    <%= @customer.first_name %><%= @customer.last_name %>さんの会員情報編集
  </h4>
  <div class="row mt-4">
    <%= form_with model: @customer, url: admin_customer_path(@customer), method: :patch do |f| %>
      <table class="table table-borderless">
        <tr>
          <td>会員ID</td>
          <td><%= f.text_field :first_name, autocomplete: "first_name" %><%= "  " %><%= f.text_field :last_name, autocomplete: "last_name" %></td>
        </tr>
        <tr>
          <td>氏名</td>
          <td><%= f.text_field :first_name_kana, autocomplete: "first_name_kana" %><%= "  " %><%= f.text_field :last_name_kana, autocomplete: "last_name_kana" %></td>
        </tr>
        <tr>
          <td>フリガナ</td>
          <td><%= f.text_field :postal_code, size: "30*30", autocomplete: "postal_code" %></td>
          <td colspan="1"></td>
        </tr>
        <tr>
          <td>郵便番号</td>
          <td><%= f.text_field :postal_code, size: "30*30", autocomplete: "postal_code" %></td>
          <td colspan="1"></td>
        </tr>
        <tr>
          <td>住所</td>
          <td><%= f.text_field :address, size: "30*30", autocomplete: "address" %></td>
          <td colspan="1"></td>
        </tr>
        <tr>
          <td>電話番号</td>
          <td><%= f.telephone_field :telephone_number, size: "30*30", autocomplete: "telephone_number" %></td>
          <td colspan="1"></td>
        </tr>
        <tr>
          <td>メールアドレス</td>
          <td><%= f.text_field :email, size: "30*30", placeholder: "0000000", autocomplete: "email" %></td>
          <td colspan="1"></td>
        </tr>
        <tr>
          <td>会員ステータス</td>
          <td>
            <%= f.label :会員ステータス %>
            <%= f.radio_button :done, true %>
            <%= f.label :is_deleted, '有効', value: '有効' %>
            <%= f.radio_button :done, false %>
            <%= f.label :is_deleted, '退会', value: '退会' %>
          </td>
        </tr>
      </table>
     <%= f.submit "変更を保存", class: "btn btn-success" %>
     <% end %>
  </div>
</div>

    <!--<tr>-->
    <!--  <th scope="row">%= f.label "販売ステータス" %></th>-->
    <!--  <td>-->
    <!--  %= f.radio_button :is_active, true %>-->
    <!--%= f.label :is_active, '販売中' %>-->
    <!--  %= f.radio_button :is_active, false %>-->
    <!--  %= f.label :is_active, '販売停止中' %>-->
    <!--  </td>-->
    <!--</tr>-->

      <%#= render "public/shared/error_messages", resource: resource %>
      <!--<thead>-->
      <!--  <tr>-->
      <!--    <td></td>-->
      <!--    <td>%= f.id %></td>-->
      <!--    <td colspan="1"></td>-->
      <!--  </tr>-->
      <!--</thead>-->
      <!--<tbody>-->
      <!--  <tr>-->
      <!--    <td>氏名</td>-->
      <!--    <td>%= f.text_field :first_name, autocomplete: "first_name" %></td>-->
      <!--    <td>%= f.text_field :last_name, autocomplete: "last_name" %></td>-->
      <!--  </tr>-->
      <!--  <tr>-->
      <!--    <td>フリガナ</td>-->
      <!--    <td>%= f.text_field :first_name_kana, autocomplete: "first_name_kana" %></td>-->
      <!--    <td>%= f.text_field :last_name_kana, autocomplete: "last_name_kana" %></td>-->
      <!--  </tr>-->
      <!--  <tr>-->
      <!--    <td>郵便番号</td>-->
      <!--    <td><= f.text_field :postal_code, autocomplete: "postal_code" %></td>-->
      <!--    <td colspan="1"></td>-->
      <!--  </tr>-->
      <!--  <tr>-->
      <!--    <td>住所</td>-->
      <!--    <td>%= f.text_area :address, size: "20", autocomplete: "address" %></td>-->
      <!--    <td colspan="1"></td>-->
      <!--  </tr>-->
      <!--  <tr>-->
      <!--    <td>電話番号</td>-->
      <!--    <td>%= f.telephone_field :telephone_number %></td>-->
      <!--    <td colspan="1">-->
      <!--    </td>-->
      <!--  </tr>-->
      <!--  <tr>-->
      <!--    <td>-->
      <!--    メールアドレス-->
      <!--    </td>-->
      <!--    <td>-->
      <!--    %= f.text_field :postal_code, placeholder: "0000000", autocomplete: "postal_code" %>-->
      <!--    </td>-->
      <!--    <td colspan="1">-->
      <!--    </td>-->
      <!--  </tr>-->
      <!--  <tr>-->
      <!--    <td>-->
      <!--    会員ステータス-->
      <!--    </td>-->
      <!--    <td>-->
      <!--    <td class="販売ステータス">-->
      <!--    %= f.label :販売ステータス %>-->
      <!--    %= f.radio_button :done, true %>-->
      <!--    %= f.label :is_deleted, '有効', value: '有効' %>-->
      <!--    %= f.radio_button :done, false %>-->
      <!--  %= f.label :is_deleted, '退会', value: '退会' %>-->
      <!--    </td>-->
      <!--  </tr>-->
      <!--</tbody>-->

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row">
    <h4 class="bg-light mt-4">
      <strong>
        会員一覧
      </strong>
    </h4>
  </div>

  <div class="row">
    <table class="table">
      <thead class="thead-light">
        <tr>
          <th>
            会員ID
          </th>
          <th>
            氏名
          </th>
          <th>
            メールアドレス
          </th>
          <th>
            ステータス
          </th>
        </tr>
      </thead>
      <tbody>
        <% @customers.each do |customer| %>
          <tr>
            <td>
              <%= customer.id %>
            </td>
            <td>
              <%= link_to admin_customer_path(customer) do %>
              <%= customer.first_name %><%= customer.last_name %>
              <% end %>
            </td>
            <td>
              <%= customer.email %>
            </td>
            <td>
              
              <% if customer.is_deleted %>
                <p class="text-secondary">
                  <strong>
                    退会済み
                  </strong>
                </p>
              <% else %>
                <p class="text-success">
                  <strong>
                    有効
                  </strong>
                </p>
              <% end %>
            </td>
        <% end %>
          </tr>
    </table>
  </div>
  <div class="row">
    <%= paginate @customers %>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">

  <h4 class="row mt-4 bg-light">
    <%= @customer.first_name %><%= @customer.last_name %>さんの会員詳細
  </h4>

  <div class="row mt-4 bg-light">
    <table class="table table-borderless">
      <thead>
        <tr>
          <td>
            会員ID
          </td>
          <td>
            <%= @customer.id %>
          </td>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>
            氏名
          </td>
          <td>
            <%= @customer.last_name %><%= @customer.first_name %>
          </td>
        </tr>
        <tr>
          <td>
            フリガナ
          </td>
          <td>
            <%= @customer.last_name_kana %><%= @customer.first_name_kana %>
          </td>
        </tr>
        <tr>
          <td>
            郵便番号
          </td>
          <td>
            <%= @customer.postal_code %>
          </td>
        </tr>
        <tr>
          <td>
            住所
          </td>
          <td>
            <%= @customer.address %>
          </td>
        </tr>
        <tr>
          <td>
            電話番号
          </td>
          <td>
            <%= @customer.telephone_number %>
          </td>
        </tr>
        <tr>
          <td>
            メールアドレス
          </td>
          <td>
            <%= @customer.email %>
          </td>
        </tr>
        <tr>
          <td>
            会員ステータス
          </td>
          <td>
            <% if @customer.is_deleted %>
              <p class="text-secondary">
                <strong>
                  退会済み
                </strong>
              </p>
            <% else %>
              <p class="text-success">
                <strong>
                  有効
                </strong>
              </p>
            <% end %>
          </td>
        </tr>
      </tbody>
    </table>
  </div>

  <div class="row">
    <div class="col-3">
      <%= link_to "編集する", edit_admin_customer_path(@customer), class: "btn btn-primary btn-sm" %>
    </div>
    <div class="col-3">
      <%= link_to admin_root_path, class: 'btn btn-info' do %>
        注文履歴一覧を見る
      <% end %>
    </div>
  </div>
</div>