config/routes.rb
Rails.application.routes.draw do

namespace :admin do
 root to:"homes#top"
 resources :items, only: [:index, :new, :create, :show, :edit, :update]
 resources :customers, only: [:index, :show, :edit, :update]
 resources :genres, only: [:index, :create, :edit, :update]
 patch 'order_details/:id' => 'order_details#update'
 resources :orders, only: [:show, :edit, :update]
 post 'items' => 'items#create'
 patch 'items/:id' => 'items#update'
 patch 'customers/:id/edit' => 'customers#update'
 end

devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

scope module: :public do
 get'homes/about' => 'homes#about', as: 'about'
 root to:"homes#top"
 resources :items, only: [:index, :show]
 delete '/cart_items/destroy_all' => 'cart_items#destroy_all', as: 'cart_items_destroy_all'
 resources :cart_items, only: [:index, :destroy, :create, :update]
 get 'orders/complete' => 'orders#complete'
 resources :orders, only: [:new, :create, :index, :show]
 resources :addresses, only: [:new, :index, :show, :create, :update, :destroy, :edit]
 get 'customers/unsubscribe' => 'customers#unsubscribe'
 get 'customers/information' => 'customers#show'
 resources :customers, only: [:show, :edit, :update, :destroy]
 get 'orders/confirm' => 'orders#confirm'
 patch '/customers/:id/withdrawal' => 'customers#withdrawal', as: 'withdrawal'
 post 'orders/confirm' => 'orders#confirm'
 post 'customers/information' => 'customers#new'
 end
end

app/models/address.rb
class Address < ApplicationRecord
belongs_to :customer

def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
end
end

app/models/admin.rb
class Admin < ApplicationRecord
  has_one_attached :image

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
belongs_to :customer
belongs_to :item

def subtotal
    item.with_tax_price * amount
end

end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def active_for_authentication?
    super && (is_deleted == false)
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
   has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :order_details, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  belongs_to :genre
  has_one_attached :profile_image
  ## 消費税を求めるメソッド
def with_tax_price
    (price * 1.1).floor
end

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image
  end

end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details, dependent: :destroy
  belongs_to :customer
  has_many :items, dependent: :destroy

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum is_active: { waiting_for_payment: 0, payment_confirmation: 1, in_production: 2, preparing_to_ship: 3, sent: 4 }

  def subtotal
    item.with_tax_price * amount
  end

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
 belongs_to :order
 belongs_to :item
 enum making_status: { cannot_be_manufactured: 0, waiting_for_production: 1, in_production: 2, completion_of_production: 3 }
end

app/models/post_image.rb
class PostImage < ApplicationRecord
  has_one_attached :image
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  def new
   @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def index
  @genres = Genre.all
  @genres = Genre.page(params[:page]).per(5)
  end

  def show
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end

  private
  def genre_params
    params.require(:genre).permit(:name)
  end

  def item_params
    params.require(:item).permit(:profile_image, :name, :introduction, :price, :is_active)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

 def top
  @order = Order.all
  @order_details = OrderDetail.page(params[:page]).per(10)
  @total = 0
 end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def new
  @item = Item.new
  end

  def create
  @item = Item.new(item_params)
  @item.save
  redirect_to admin_item_path(@item.id)
  end

  def index
  @items = Item.all
  @items = Item.page(params[:page]).per(10)
  @genres = Genre.all
  end

  def show
  @post_image = PostImage.new
  @item = Item.find(params[:id])
  @items = Item.all
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :price, :is_active, :profile_image, :genre_id)
  end

  def genre_params
    params.require(:genre).permit(:name)
  end

  end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

 def show
  @order = Order.find(params[:id])
  @customer = @order.customer
  @order_details = @order.order_details
  @total = 0
  @shopping_cost = 800
 end

  # def show
  #   @order = Order.find(params[:id])
  #   @order_details = @order.order_details
  # end

 def update
   @order = Order.find(params[:id])
   @order.update(order_params)
   redirect_to order_path
 end

 private
 def order_params
  params.require(:order).permit(:payment_method, :postal_code, :address, :name, :total_price, :is_active)
 end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    customers_information_path(current_customer.id)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">
<h4 class="row mt-4 bg-light">
ジャンル編集
</h4>

<%= form_with model: @genre, url: admin_genre_path(@genre.id), method: :patch do |f| %>
<table class="table table-borderless">
    <tr>
      <th>ジャンル名 <%= f.text_field :name %><%= f.submit "変更を保存", class: "btn btn-success" %></th>
    </tr>
</table>
<% end %>

app/views/admin/genres/index.html.erb
<div class="container">
  <div class="row mt-4 bg-light">
    <h4><strong>ジャンル一覧・追加</strong></h4>
  </div>
  <div class="row">
    <table class="table table-borderless">
      <%= form_with model: Genre.new, url: admin_genres_path, method: :post do |f| %>
      <tr>
        <th>
        ジャンル名<%= "  " %>
        <%= f.text_field :name %><%= "  " %><%= f.submit "新規登録", class: "btn btn-success" %>
        <% end %>
        </th>
      </tr>
    </table>
  </div>
  <div class="row">
    <table class="table">
      <thead class="thead-light">
        <tr>
          <th>ジャンル</th>
          <th></th>
        </tr>
      </thead>
        <% @genres.each do |t| %>
      <tbody>
        <tr>
          <th><%= t.name %></th>
          <th><%= link_to "編集する", edit_admin_genre_path(t.id), class: "btn btn-success mt-2" %></th>
        </tr>
      </tbody>
      <% end %>
    </table>
  </div>
  <div class="row">
    <%= paginate @genres %>
  </div>
</div>

app/views/admin/homes/top.html.erb
<div class="container">
  <div class="row">
    <h4 class="col-md-8 offset-md-1 mt-4 bg-light">
      <strong>注文履歴一覧</strong>
    </h4>
  </div>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">購入日時</th>
        <th scope="col">購入者</th>
        <th scope="col">注文個数</th>
      </tr>
    </thead>
    <% @order.each do |order| %>
    <tbody>
      <tr>
        <td>
        <%= link_to admin_order_path(order) do %>
        <%= order.created_at %>
        <% end %>
        </td>
        <td>
        <%= order.customer.first_name %>
        <%= order.customer.last_name %>
        </td>
        <td>
        <% @total = 0 %>
        <% order.order_details.each do |order_detail| %>
        <% @total = @total + order_detail.amount %>
        <% end %>
        <%= @total %>
        </td>
      </tr>
    </tbody>
    <% end %>
  </table>

</div>
  <div class="row">
    <%= paginate @order_details %>
  </div>

app/views/admin/items/edit.html.erb
<%= flash[:notice] %>

<div class="container">
<h4 class="row mt-4 bg-light">
<strong>商品編集</strong></h4>
<%= form_with model: @item, url: admin_item_path(@item.id), method: :patch do |f| %>
<table class="table table-borderless">
  <thead>
    <tr>
      <th><label for="inputImage" class="col-form-label mt-4">商品画像</label></th>
      <th><%= f.file_field :profile_image, accept: "image/*" %></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">商品名</th>
      <td><%= f.text_field :name %></td>
    </tr>
    <tr>
      <th scope="row">商品説明</th>
      <td><%= f.text_area :introduction %></td>
    </tr>
    <tr>
      <th scope="row">ジャンル</th>
      <td><%= f.collection_select :genre_id, Genre.all, :id, :name %></td>
    </tr>
    <tr>
      <th scope="row">税抜価格</th>
      <td><%= f.text_field :price %>円</td>
    </tr>
    <tr>
      <th scope="row"><%= f.label "販売ステータス" %></th>
      <td>
      <%= f.radio_button :is_active, true %>
      <%= f.label :is_active, '販売中' %>
      <%= f.radio_button :is_active, false %>
      <%= f.label :is_active, '販売停止中' %>
      </td>
    </tr>
  </tbody>
</table>
    <div class="row mx-4">
    <%= f.submit '変更を保存', class: "btn btn-success" %>
    <% end %>
    </div>
</div>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="row">
    <h4 class="col-md-8 offset-md-1 mt-4 bg-light">
      <strong>商品一覧</strong>
    </h4>
    <div class="col-md-3 mt-4">
      <%= link_to new_admin_item_path, class: 'nav-link' do %>
        <i class="fas fa-plus"></i>
      <% end %>
    </div>
  </div>
  <div class="row">
    <table class="table">
      <thead>
        <tr>
          <th>商品ID</th>
          <th>商品名</th>
          <th>税抜価格</th>
          <th>ジャンル</th>
          <th>ステータス</th>
        </tr>
      </thead>
      <% @items.each do |t| %>
      <tbody>
        <tr>

        <td>
        <%= t.id %>
        </td>

        <td>
    　　<%= link_to t.name, admin_item_path(t) %>
        </td>

        <td>
        <%= t.price %>
        </td>

        <td>
        <%= t.genre.name %>
        </td>
        <!--アソシエーション（？？）-->

        <td>
        <% if t.is_active == false %>
        <p class="text-secondary"><strong>販売停止中</strong></p>
        <% else %>
        <p class="text-success"><strong>販売中</strong></p>
        <% end %>
        </td>
        <% end %>
        </table>
    </div>

    <div class="row">
    <%= paginate @items %>
    </div>

app/views/admin/items/new.html.erb
<div class="container">
<h4 class="row mt-4 bg-light">
<strong>商品新規登録</strong></h4>

<%= form_with model: @item, url: admin_items_path, method: :post do |f| %>
 <table class="table table-borderless">
  <thead>
    <tr>
      <td>商品画像</td>
      <td><%= f.file_field :profile_image, placeholder: "選択されていません", accept: "image/*" %></td>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>商品名</td>
      <td><%= f.text_field :name, placeholder: "商品名"%></td>
    </tr>
    <tr>
      <td>商品説明</td>
      <td><%= f.text_area :introduction, placeholder: "ここに説明文を記述します"%></td>
    </tr>
    <tr>
      <td>ジャンル</td>
      <td><%= f.collection_select :genre_id, Genre.all, :id, :name %></td>
    </tr>
    <tr>
      <td>税抜価格</td>
      <td><%= f.text_area :price, placeholder: "1000" %></td>
    </tr>
    <tr>
      <td>販売ステータス</td>
      <td><div class="販売ステータス">
      <%= f.label :販売ステータス %>
      <%= f.radio_button :done, true %>
      <%= f.label :is_active, '販売中', value: '販売中' %>
      <%= f.radio_button :done, false %>
      <%= f.label :is_active, '販売停止中', value: '販売停止中' %></div></td>
    </tr>
  </tbody>
</table>
<%= f.submit '新規登録', class: "btn btn-success mb-3" %>
<% end %>
</div>

app/views/admin/items/show.html.erb
<%= flash[:notice] %>
<div class="container">

<h4 class="row mt-4 bg-light">
<strong>商品詳細</strong>
</h4>

<div class="row mt-4">
<div class="col-lg-6">
<%= image_tag @item.get_profile_image(100,100), width: '80%', height: '80%' %>
</div>

<div class="col-lg-6">

<table class="table table-borderless">
    <tr>
      <th scope="col">商品名</th>
      <th scope="col"><%= @item.name %></th>
    </tr>
    <tr>
      <th scope="col">商品説明</th>
      <th scope="col"><%= @item.introduction %></th>
    </tr>
    <tr>
      <th scope="col">ジャンル</th>
      <th scope="col"><%= @item.genre.name %></th>
    </tr>
    <tr>
      <th scope="col">税込価格(税抜価格)</th>
      <th scope="col"><%= @item.price %></th>
    </tr>
    <tr>
      <th scope="col">販売ステータス</th>
      <th scope="col">
      <% if @item.is_active == false %>
      <p class="text-secondary"><strong>販売停止中</strong></p>
      <% else %>
      <p class="text-success"><strong>販売中</strong></p>
      <% end %>
      </th>
    </tr>
</table>

<div class="row mt-4">
<%= form_with model: @item, method: :edit do |t| %>
<td><%= link_to "編集する", edit_admin_item_path, class: "btn btn-success" %></td><p>
<% end %>
</div>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
  <h4 class="row mt-4 bg-light">
    注文履歴詳細
  </h4>
    <table class="table table-borderless">
      <thead>
        <tr>
          <th><strong>購入者</strong></th>
          <th>
          <%= link_to admin_customer_path(@customer) do %>
          <%= @customer.first_name %><%= @customer.last_name %>
          <% end %>
          </th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th><strong>注文日</strong></th>
          <td><%= @order.created_at %></td>
        </tr>
        <tr>
          <th><strong>配送先</strong></th>
          <td><%= @order.address %></td>
        </tr>
        <tr>
          <th><strong>支払方法</strong></th>
          <td><%= @order.payment_method_i18n %></td>

        </tr>
        <tr>
          <th><strong>注文ステータス</strong></th>
          <td>
            <%= form_with model: @order, url: admin_order_path, method: :patch do |f| %>
            <%= f.select :is_active, Order.is_actives_i18n.invert %>
            <%= f.submit "更新", class: "btn btn-success" %>
          </td>
        </tr>
      </tbody>
      <% end %>
    </table>

  <div class="row">
    <div class="col-7">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>商品名</th>
            <th>単価（税込）</th>
            <th>数量</th>
            <th>小計</th>
            <th>製作ステータス</th>
          </tr>
        </thead>
          <% @order_details.each do |order_detail| %>
          <% @total += (order_detail.price * order_detail.amount*1.1).floor %>
        <tbody>
          <tr>
            <th><%= order_detail.item.name %></th>
            <th><%= order_detail.item.with_tax_price %></th>
            <th><%= order_detail.amount %></th>
            <%#= order_detail.item.with_tax_price * order.amount %>
            <th class="col-xs-2">¥<%= ((order_detail.price * order_detail.amount*1.1).floor).to_s(:delimited) %></td>
            <th>
            <%= form_with model: order_detail, url: admin_path(order_detail), method: :patch do |f| %>
            <%= f.select :making_status, OrderDetail.making_statuses_i18n.invert %>
            <%#= f.select :making_status, ["製作不可", "製作待ち", "製作中", "製作完了"] %>
            <%= f.submit "更新", class: "btn btn-success" %>
            </th>
          </tr>
        </tbody>
        <% end %>
        <% end %>
      </table>
    </div>

    <div class="col-5">
      <table class="table table-borderless">
        <thead>
          <tr>
            <th><strong>商品合計</strong><%= "  " + "  " %><%= @total %>円</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th><strong>送料</strong><%= "  " + "  " %><%= @shopping_cost %>円</th>
          </tr>
          <tr>
            <th><strong>請求金額合計</strong><%= "  " + "  " %><%= @total + @shopping_cost %>円</th>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>