config/routes.rb
Rails.application.routes.draw do

namespace :admin do
 root to:"homes#top"
 resources :items, only: [:index, :new, :create, :show, :edit, :update]
 resources :customers, only: [:index, :show, :edit, :update]
 resources :genres, only: [:index, :create, :edit, :update]
 patch 'order_details/:id' => 'order_details#update'
 resources :orders, only: [:show, :edit, :update]
 post 'items' => 'items#create'
 patch 'items/:id' => 'items#update'
 patch 'customers/:id/edit' => 'customers#update'
 end

devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

scope module: :public do
 get'homes/about' => 'homes#about', as: 'about'
 root to:"homes#top"
 resources :items, only: [:index, :show]
 delete '/cart_items/destroy_all' => 'cart_items#destroy_all', as: 'cart_items_destroy_all'
 resources :cart_items, only: [:index, :destroy, :create, :update]
 get 'orders/complete' => 'orders#complete'
 resources :orders, only: [:new, :create, :index, :show]
 resources :addresses, only: [:new, :index, :show, :create, :update, :destroy, :edit]
 get 'customers/unsubscribe' => 'customers#unsubscribe'
 get 'customers/information' => 'customers#show'
 resources :customers, only: [:show, :edit, :update, :destroy]
 get 'orders/confirm' => 'orders#confirm'
 patch '/customers/:id/withdrawal' => 'customers#withdrawal', as: 'withdrawal'
 post 'orders/confirm' => 'orders#confirm'
 post 'customers/information' => 'customers#new'
 end
end

app/models/address.rb
class Address < ApplicationRecord
belongs_to :customer

def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
end
end

app/models/admin.rb
class Admin < ApplicationRecord
  has_one_attached :image

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
belongs_to :customer
belongs_to :item

def subtotal
    item.with_tax_price * amount
end

end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def active_for_authentication?
    super && (is_deleted == false)
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
   has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :order_details, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  belongs_to :genre
  has_one_attached :profile_image
  ## 消費税を求めるメソッド
def with_tax_price
    (price * 1.1).floor
end

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image
  end

end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details, dependent: :destroy
  belongs_to :customer
  has_many :items, dependent: :destroy

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum is_active: { waiting_for_payment: 0, payment_confirmation: 1, in_production: 2, preparing_to_ship: 3, sent: 4 }

  def subtotal
    item.with_tax_price * amount
  end

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
 belongs_to :order
 belongs_to :item
 enum making_status: { cannot_be_manufactured: 0, waiting_for_production: 1, in_production: 2, completion_of_production: 3 }
end

app/models/post_image.rb
class PostImage < ApplicationRecord
  has_one_attached :image
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

 def top
  @order = Order.all
  @order_details = OrderDetail.page(params[:page]).per(10)
  @total = 0
 end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def new
  @item = Item.new
  end

  def create
  @item = Item.new(item_params)
  @item.save
  redirect_to admin_item_path(@item.id)
  end

  def index
  @items = Item.all
  @items = Item.page(params[:page]).per(10)
  @genres = Genre.all
  end

  def show
  @post_image = PostImage.new
  @item = Item.find(params[:id])
  @items = Item.all
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :price, :is_active, :profile_image, :genre_id)
  end

  def genre_params
    params.require(:genre).permit(:name)
  end

  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    customers_information_path(current_customer.id)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
<body>
  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light  bg-dark">
        <div class="container">
          <a class="navbar-brand p-2 text-white" href="/">LOGO</a>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
</div>



<% if customer_signed_in? %>
<li>
<%= link_to customer_path(current_customer), class: 'nav-link text-white' do %>
<i class="fas fa-users"></i>マイページ
<% end %>
</li>

<li>
<%= link_to items_path, class: 'nav-link text-white' do %>
<i class="fas fa-home"></i>商品一覧
<% end %>
</li>

<li>
<%= link_to cart_items_path, class: 'nav-link text-white' do %>
<i class="fas fa-sign-out-alt"></i>カート
<% end %>
</li>

<li>
<%= link_to destroy_customer_session_path, class: 'nav-link text-white', method: :delete do %>
<i class="fas fa-sign-out-alt"></i>ログアウト
<% end %>
</li>

<% elsif admin_signed_in? %>

<li>
<%= link_to admin_items_path, class: 'nav-link text-white' do %>
<i class="fas fa-home"></i>商品一覧
<% end %>
</li>


<li>
<%= link_to admin_customers_path, class: 'nav-link text-white' do %>
<i class="fas fa-users"></i>会員一覧
<% end %>
</li>

<li>
<%= link_to admin_root_path, class: 'nav-link text-white' do %>
<i class="fas fa-sign-out-alt"></i>注文履歴一覧
<% end %>
</li>

<li>
<%= link_to admin_genres_path, class: 'nav-link text-white' do %>
<i class="fas fa-sign-out-alt"></i>ジャンル一覧
<% end %>
</li>

<li>
<%= link_to destroy_admin_session_path, class: 'nav-link text-white', method: :delete do %>
<i class="fas fa-sign-out-alt"></i>ログアウト
<% end %>
</li>

<% else %>
<li>
<%= link_to about_path, class: 'nav-link text-white' do %>
<i class="fas fa-link"></i>About
<% end %>
</li>


<li>
<%= link_to items_path, class: 'nav-link text-white' do %>
<i class="fas fa-home"></i>商品一覧
<% end %>
</li>


<li>
<%= link_to new_customer_registration_path, class: 'nav-link text-white' do %>
<i class="fas fa-user-plus"></i>新規登録
<% end %>
</li>

<li>
<%= link_to new_customer_session_path, class: 'nav-link text-white' do %>
<i class="fas fa-sign-in-alt"></i>ログイン
<% end %>
</li>
<% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="mb-auto">
<div class="fixed-bottom">
<div class="row">
<div class="mx-auto">
CopyRight Infratop.inc
</div>
</div>
</div>
    <%= yield %>
  </body>
</html>